name: Gatsby Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: enriikke/gatsby-gh-pages-action@v2.2.0
      with:
        access-token: ${{ secrets.GH_PAGES_TOKEN }}
        skip-publish: true
        gatsby-args: --prefix-paths
